name = "website"
type = "webpack"
account_id = "814334ab66c619c9517a2d66d47b1164"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "./workers-site/webpack.config.js"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
name = "staging"
workers_dev = true
route = "staging.viranchee.com/*"

[env.production]
# name = "website"